# Generated by tools/build_game_over_music.py; do not edit.
# RARS MIDI events: start_ms, duration_ms, pitch, velocity.

.eqv GAME_OVER_MUSIC_EVENT_COUNT 12
.eqv GAME_OVER_MUSIC_LOOP_MS 72256
.eqv GAME_OVER_MUSIC_INSTRUMENT 88
.eqv GAME_OVER_MUSIC_STOP_PITCH_COUNT 10
.eqv GAME_OVER_MUSIC_ENABLED 1

.data
.align 2
game_over_music_index:      .word 0
game_over_music_loop_start: .word 0

game_over_music_events:
    .word 0, 34560, 24, 70
    .word 1632, 5888, 46, 46
    .word 7296, 34560, 23, 70
    .word 8704, 6624, 43, 46
    .word 14416, 5888, 50, 46
    .word 14592, 34560, 26, 70
    .word 21488, 6624, 41, 46
    .word 21888, 40320, 27, 70
    .word 28832, 5888, 45, 46
    .word 30400, 34560, 24, 70
    .word 34272, 6624, 38, 46
    .word 37696, 34560, 23, 70

game_over_music_stop_pitches:
    .byte 23, 24, 26, 27, 38, 41, 43, 45, 46, 50
