"""Build the phase-3 laboratory map and its 114-pixel exit overlay."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "assets" / "source" / "backgrounds"
GENERATED_DIR = ROOT / "assets" / "generated"
BASE_SOURCE = SOURCE_DIR / "laboratory_base.png"
HIGHLIGHT_SOURCE = SOURCE_DIR / "laboratory_exit_highlight.png"
SCREEN_SIZE = (320, 240)
PIXEL_COUNT = 76_800
EXIT_OVERLAY_PIXEL_COUNT = 114
DOMINANT_FLOOR_RGB = (208, 208, 198)
# 5/16 de branco misturado a 11/16 de cinza neutro aproxima o piso da
# PNG sem o amarelo/azul forte produzido pela quantizacao independente.
DOMINANT_BASE_VALUE = 0xAD
DOMINANT_DITHER_VALUE = 0xFF
BAYER_4X4 = (
    (0, 8, 2, 10),
    (12, 4, 14, 6),
    (3, 11, 1, 9),
    (15, 7, 13, 5),
)

ASSEMBLY_PATH = GENERATED_DIR / "laboratory_bgr233.s"
BASE_BIN_PATH = GENERATED_DIR / "laboratory_bgr233_base.bin"
OVERLAY_BIN_PATH = GENERATED_DIR / "laboratory_bgr233_exit_overlay.bin"
PREVIEW_PATH = GENERATED_DIR / "laboratory_bgr233_preview.png"
HIGHLIGHT_PREVIEW_PATH = GENERATED_DIR / "laboratory_bgr233_highlight_preview.png"
METRICS_PATH = GENERATED_DIR / "laboratory_bgr233_metrics.json"


@dataclass(frozen=True)
class BuildResult:
    source_size: tuple[int, int]
    sources_opaque: bool
    original_difference_offsets: tuple[int, ...]
    base: bytes
    highlight: bytes
    overlay: tuple[tuple[int, int], ...]
    preview_base_rgb: tuple[tuple[int, int, int], ...]
    files: dict[Path, bytes]
    metrics: dict[str, object]


def encode_bgr233(red: int, green: int, blue: int) -> int:
    red_level = round(red * 7 / 255)
    green_level = round(green * 7 / 255)
    blue_level = round(blue * 3 / 255)
    return (blue_level << 6) | (green_level << 3) | red_level


def encode_laboratory_pixel(red: int, green: int, blue: int, x: int, y: int) -> int:
    """Convert one source pixel, perceptually matching the dominant floor."""
    if (red, green, blue) == DOMINANT_FLOOR_RGB:
        if BAYER_4X4[y & 3][x & 3] < 5:
            return DOMINANT_DITHER_VALUE
        return DOMINANT_BASE_VALUE
    return encode_bgr233(red, green, blue)


def decode_bgr233(value: int) -> tuple[int, int, int]:
    return (
        round((value & 7) * 255 / 7),
        round(((value >> 3) & 7) * 255 / 7),
        round(((value >> 6) & 3) * 255 / 3),
    )


def load_sources() -> tuple[Image.Image, Image.Image, bool]:
    with Image.open(BASE_SOURCE) as opened:
        base = opened.convert("RGBA")
    with Image.open(HIGHLIGHT_SOURCE) as opened:
        highlight = opened.convert("RGBA")
    if base.size != SCREEN_SIZE or highlight.size != SCREEN_SIZE:
        raise ValueError(f"Laboratory sources must be 320x240; got {base.size} and {highlight.size}")
    pixels = tuple(base.get_flattened_data()) + tuple(highlight.get_flattened_data())
    opaque = all(pixel[3] == 255 for pixel in pixels)
    if not opaque:
        raise ValueError("Laboratory sources must be fully opaque")
    return base, highlight, opaque


def png_bytes(pixels: tuple[tuple[int, int, int], ...]) -> bytes:
    image = Image.new("RGB", SCREEN_SIZE)
    image.putdata(pixels)
    output = BytesIO()
    image.save(output, format="PNG", optimize=False)
    return output.getvalue()


def render_assembly(base: bytes, overlay: tuple[tuple[int, int], ...]) -> bytes:
    lines = [
        "# Generated by tools/build_laboratory_bgr233.py; do not edit.",
        "# BGR233 8bpp (BBGGGRRR), 320x240, perceptual floor dithering.",
        "",
        ".data",
        ".align 2",
        "",
        f"# payload-bytes: {len(base)}",
        "laboratory_bgr233_base_pixels:",
    ]
    for offset in range(0, len(base), 32):
        lines.append("    .byte " + ", ".join(f"0x{value:02X}" for value in base[offset:offset + 32]))
    lines.extend(("", f"# overlay-pixels: {len(overlay)}", "laboratory_bgr233_exit_overlay_pixels:"))
    words = tuple((offset << 8) | value for offset, value in overlay)
    for offset in range(0, len(words), 8):
        lines.append("    .word " + ", ".join(f"0x{value:08X}" for value in words[offset:offset + 8]))
    return ("\n".join(lines) + "\n").encode("ascii")


def build(*, write: bool = True) -> BuildResult:
    base_source, highlight_source, opaque = load_sources()
    base_pixels = tuple(base_source.get_flattened_data())
    highlight_pixels = tuple(highlight_source.get_flattened_data())
    difference_offsets = tuple(
        offset for offset, pair in enumerate(zip(base_pixels, highlight_pixels)) if pair[0] != pair[1]
    )
    if len(difference_offsets) != EXIT_OVERLAY_PIXEL_COUNT:
        raise ValueError(f"Laboratory overlay must contain 114 coordinates, got {len(difference_offsets)}")

    base = bytes(
        encode_laboratory_pixel(red, green, blue, offset % SCREEN_SIZE[0], offset // SCREEN_SIZE[0])
        for offset, (red, green, blue, _) in enumerate(base_pixels)
    )
    highlighted = bytearray(base)
    for offset in difference_offsets:
        red, green, blue, _ = highlight_pixels[offset]
        highlighted[offset] = encode_laboratory_pixel(
            red, green, blue, offset % SCREEN_SIZE[0], offset // SCREEN_SIZE[0]
        )
    highlight = bytes(highlighted)
    actual_differences = tuple(
        offset for offset, pair in enumerate(zip(base, highlight)) if pair[0] != pair[1]
    )
    if actual_differences != difference_offsets:
        raise RuntimeError("Converted Laboratory overlay does not preserve the exact 114-pixel mask")

    overlay = tuple((offset, highlight[offset]) for offset in difference_offsets)
    preview_base_rgb = tuple(decode_bgr233(value) for value in base)
    preview_highlight_rgb = tuple(decode_bgr233(value) for value in highlight)
    overlay_binary = b"".join(struct.pack("<I", (offset << 8) | value) for offset, value in overlay)
    mean_error = sum(
        abs(source - converted)
        for rgba, converted_rgb in zip(base_pixels, preview_base_rgb)
        for source, converted in zip(rgba[:3], converted_rgb)
    ) / (PIXEL_COUNT * 3)
    metrics: dict[str, object] = {
        "conversion": "nearest_bgr233_with_ordered_dominant_floor_mix",
        "mean_absolute_rgb_error": round(mean_error, 4),
        "dominant_floor_source_rgb": DOMINANT_FLOOR_RGB,
        "dominant_floor_base_rgb": decode_bgr233(DOMINANT_BASE_VALUE),
        "dominant_floor_dither_rgb": decode_bgr233(DOMINANT_DITHER_VALUE),
        "dominant_floor_dither_fraction": 0.3125,
        "source_difference_pixels": len(difference_offsets),
        "converted_difference_pixels": len(actual_differences),
        "overlay_coordinates_match": actual_differences == difference_offsets,
        "overlay_bbox": (299, 10, 310, 58),
        "hashes": {
            "base_sha256": hashlib.sha256(base).hexdigest(),
            "highlight_sha256": hashlib.sha256(highlight).hexdigest(),
            "overlay_sha256": hashlib.sha256(overlay_binary).hexdigest(),
        },
    }
    files = {
        ASSEMBLY_PATH: render_assembly(base, overlay),
        BASE_BIN_PATH: base,
        OVERLAY_BIN_PATH: overlay_binary,
        PREVIEW_PATH: png_bytes(preview_base_rgb),
        HIGHLIGHT_PREVIEW_PATH: png_bytes(preview_highlight_rgb),
        METRICS_PATH: (json.dumps(metrics, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    }
    if write:
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        for path, payload in files.items():
            path.write_bytes(payload)
    return BuildResult(
        source_size=base_source.size,
        sources_opaque=opaque,
        original_difference_offsets=difference_offsets,
        base=base,
        highlight=highlight,
        overlay=overlay,
        preview_base_rgb=preview_base_rgb,
        files=files,
        metrics=metrics,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = build(write=False)
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, payload in result.files.items()
                 if not path.exists() or path.read_bytes() != payload]
        if stale:
            print("stale generated Laboratory files: " + ", ".join(stale))
            return 1
        print("Laboratory BGR233 generated files: PASS")
        return 0
    for path, payload in result.files.items():
        path.write_bytes(payload)
    print(json.dumps({"base_bytes": len(result.base), "overlay_pixels": len(result.overlay)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
