"""Convert the 320x240 cutscenes to RARS16 Custom1 BGR233 bytes."""

import argparse

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "assets" / "source" / "cutscenes"
OUTPUT = ROOT / "assets" / "generated" / "cutscenes.s"
SCREEN_SIZE = (320, 240)
SOURCES = (
    ("cutscene_intro.png", "cutscene_intro_pixels"),
    ("cutscene_level2.png", "cutscene_level2_pixels"),
    ("cutscene_level3.png", "cutscene_level3_pixels"),
    ("post_boss_detonator.png", "cutscene_post_boss_detonator"),
    ("post_boss_explosion.png", "cutscene_post_boss_explosion"),
)


def encode_bgr233(red: int, green: int, blue: int) -> int:
    return ((blue >> 6) << 6) | ((green >> 5) << 3) | (red >> 5)


def convert(path: Path) -> bytes:
    with Image.open(path) as source:
        image = source.convert("RGBA")

    if image.size != SCREEN_SIZE:
        raise ValueError(f"{path.name}: expected 320x240, got {image.width}x{image.height}")

    pixels = list(image.get_flattened_data())
    if any(alpha != 255 for _, _, _, alpha in pixels):
        raise ValueError(f"{path.name}: cutscenes must be fully opaque")

    return bytes(encode_bgr233(red, green, blue) for red, green, blue, _ in pixels)


def render() -> str:
    lines = [
        "# Generated by tools/convert_cutscenes.py; do not edit.",
        "# RARS16 Custom1 BGR233 direct 8bpp, 320x240, row-major.",
        "",
        ".data",
        ".align 2",
    ]

    for filename, label in SOURCES:
        payload = convert(SOURCE_DIR / filename)
        lines.extend(("", f"# source: assets/source/cutscenes/{filename}", f"# payload-bytes: {len(payload)}", f"{label}:"))
        for offset in range(0, len(payload), 32):
            chunk = payload[offset : offset + 32]
            lines.append("    .byte " + ", ".join(f"0x{value:02X}" for value in chunk))

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="ascii") != generated:
            print("assets/generated/cutscenes.s is missing or stale")
            return 1
        return 0

    OUTPUT.write_text(generated, encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
